version: "3.8"

services:
  backend:
    build: .
    container_name: backend_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - database
    ports:
      - "9000:9000"

volumes:
  db_data:
